# conda env create -f environment.yml
name: birdy
channels:
  - conda-forge
  - bokeh
  - defaults
dependencies:
  - matplotlib
  - xarray
  - numpy
  # avoid owslib 0.22 with timeout bug
  # https://github.com/geopython/OWSLib/issues/737
  - owslib==0.21.0
  - netcdf4
  - pydap
  - ipyleaflet
  - bokeh
  - jupyter_bokeh
  - panel
  - holoviews
  - geoviews
  # this might still be relevant https://github.com/holoviz/hvplot/issues/498
  # (violin plot not working with hvplot 0.6.0).
  # Per this comment
  # https://github.com/bird-house/birdhouse-deploy/pull/63#issuecomment-668270608
  # pinning hvplot did not solve the problem with violin plot.
  - hvplot
  # tests
  - pytest
  - nbval
  # to edit .ipynb
  - jupyter
  # to be launched by image jupyterhub/jupyterhub
  - notebook
  - jupyterlab==2.2.9
  - jupyterhub
  # to diff .ipynb files
  - nbdime
  # extension to produce .py files from notebook .ipynb files
  # fix to 1.8.2 since latest version is only compatible with jupyterlab 3.0
  - jupytext==1.8.2
  # jupyterlab extension for git
  - jupyterlab-git
  # jupyterlab extension for conda
  - jupyter_conda
  - jupyter-archive
  # utilities
  - curl
  - wget
  # for pip packages
  - pip
  - pip:
    - birdhouse-birdy
    - requests-magpie
