# conda env create -f environment.yml
name: birdy
channels:
  - conda-forge
  - cdat
  - bokeh
  - plotly  # for jupyter-dash
  - defaults
dependencies:
  - matplotlib
  - xarray
  - numpy
#  - birdy
  - owslib>=0.19.0
  - netcdf4
  - pydap
  - cartopy
  - descartes
  - rasterio
  - gdal  # for osgeo
  - geopandas
  - pandas
  - rioxarray
  - scikit-image
  - ipyleaflet
  - threddsclient
  - bokeh
  - regionmask
  - siphon
  - jupyter_bokeh
  - pscript
  - h5netcdf
  - panel
  - holoviews
  - geoviews
  # this might still be relevant https://github.com/holoviz/hvplot/issues/498
  # (violin plot not working with hvplot 0.6.0).
  # Per this comment
  # https://github.com/bird-house/birdhouse-deploy/pull/63#issuecomment-668270608
  # pinning hvplot did not solve the problem with violin plot.
  - hvplot
  - nc-time-axis
  - xclim
  # https://anaconda.org/anaconda/memory_profiler
  # Monitor memory consumption of a process as well as line-by-line analysis
  # of memory consumption for Python programs.
  - memory_profiler
  # for esgf notebooks
  - esgf-compute-api
  - cdms2
  - vcs
  - mesalib
  # tests
  - pytest
  - nbval
  # to edit .ipynb
  - jupyter
  # to be launched by image jupyterhub/jupyterhub
  - notebook
  - jupyterlab
  - jupyterhub
  # to diff .ipynb files
  - nbdime
  # extension to produce .py files from notebook .ipynb files
  - jupytext
  # jupyterlab extension for git
  - jupyterlab-git
  # jupyterlab extension for conda
  - jupyter_conda
  # Voila turns Jupyter notebooks into standalone web applications
  - voila
  - jupyter-archive
  # xeus-python: back-end kernel implementing the Jupyter Debug Protocol
  - xeus-python
  - jupyter-dash
  # utilities
  - curl
  - wget
  # for pip packages
  - pip
  - pip:
    - birdhouse-birdy
    # visual debugger for Jupyter Notebook, not working with JupyterLab at this moment
    - pixiedust
    - requests-magpie
    # block execution of 'run_all_cells' until user input finished
    - ipython_blocking
    # Mimics how one might format their calculation if it were written with a
    # pencil: write the symbolic formula, followed by numeric substitutions,
    # and then the result.
    - handcalcs
    # https://github.com/ShopRunner/jupyter-notify
    # Jupyter Magic For Browser Notifications of Cell Completion.
    - jupyternotify
    # Needed for https://github.com/jtpio/jupyterlab-topbar
    - nbresuse
    # Needed to run notebook tests.  Missing indirect recursive dependencies
    # somewhere, should not need to manually add it here.
    - pytest-tornasync
