# This file contains the packages developed by or that receive any contribution by CRIM and/or Ouranos.
# The purpose of this file is to isolate packages which receive an active contribution and which will require more
# frequent updates.
name: birdy
channels:
  - conda-forge
dependencies:
  - owslib>=0.23.0
  - birdy
  # for pip packages, include even if already in environment_main.yml, to avoid a warning problem on DockerHub
  - pip
  - pip:
    - requests-magpie
