# This file contains the packages related to jupyter plugins and extensions
name: birdy
channels:
  - conda-forge
  - defaults
dependencies:
  # to diff .ipynb files
  - nbdime
  # extension to produce .py files from notebook .ipynb files
  - jupytext
  - jupyterlab-git
  - jupyter_conda
  - packaging
  - jupyter-archive
  # Extension can now be installed using pip with jupyterlab >= 3.0
  - jupyterlab_widgets
  - ipywidgets
  - pyviz_comms
  - jupyter_bokeh
