# This file contains the main required packages (such as jupyter) and other generic utilities
name: birdy
channels:
  - conda-forge
  - defaults
dependencies:
  # to edit .ipynb
  - jupyter
  # to be launched by image jupyterhub/jupyterhub
  - notebook
  - jupyterlab==2.2.9
  - jupyterhub
  # utilities
  - curl
  - wget
  # to read yaml files from the deploy scripts for the notebooks in JupyterHub
  - yq
  # for pip packages
  - pip
